services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: marketplace
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: {}